import React, { Component } from "react";
import API from "../../utils/API";
import "./style.css";

class Items extends Component {
  state = {
    saved: "",
    disabled: false,
    saveText: "Save",
  };

  // Runs the get book function for each rendered book object
  componentDidMount() {
    this.getBook(this.props.title);
  }

  // After clicking the save button this function runs and builds an
  // object from params and uses it to call the savebook function
  makeBook = () => {
    let obj = {};

    obj.title = this.props.title;
    obj.authors = this.props.authors;
    obj.description = this.props.description;
    obj.id = this.props.id;
    obj.image = this.props.image;
    obj.link = this.props.link;

    this.saveBook(obj);

    this.setState({
      saveText: "Saved",
      disabled: true,
    });
  };

  // This function takes the obj generated by the makebook function
  // and uses it to save the book to the DB.
  saveBook = (bookData) => {
    API.saveBook(bookData)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  // When rendering book media objects into the page from the API, this
  // function checks if it exists in the DB first and disables the save
  // button if it does.
  getBook = (id) => {
    API.getBook(id)
      .then((res) => {
        // console.log(res.data)
        if (res.data === null) {
          this.setState({
            saved: false,
          });
        } else {
          return this.setState({
            saved: true,
          });
        }
      })
      .catch((err) => {
        console.log(err);
      });
  };

  render() {
    return (
      <div id={this.props.id} className="media mediaBox">
        <img
          src={this.props.image}
          className="align-self-center mr-3 bookImg"
          alt="..."
        />
        <div className="media-body align-self-center">
          <h4 className="my-0">{this.props.title}</h4>
          <p>
            <small> - {this.props.authors}</small>
          </p>
          <p className="mediaText">{this.props.description}</p>
          <a href={this.props.link} target="_blank" rel="noopener noreferrer">
            <button type="button" className="btn btn-primary btn-sm ml-2">
              Visit
            </button>
          </a>
          {(() => {
            if (this.state.saved) {
              return (
                <button
                  type="button"
                  className="btn btn-success btn-sm ml-2"
                  disabled
                >
                  Saved
                </button>
              );
            } else {
              return (
                <button
                  onClick={() => this.makeBook()}
                  type="button"
                  className={`btn btn-success btn-sm ml-2`}
                  disabled={this.state.disabled}
                >
                  {this.state.saveText}
                </button>
              );
            }
          })()}
        </div>
      </div>
    );
  }
}

export default Items;
